<?php
/**
 * @file
 * Web server node type is defined here.
 */

/**
 * Implements hook_hosting_service().
 */
function hosting_docker_server_hosting_service() {
  return array(
    'apache_docker' => 'http',
    'mysql_docker' => 'db',
  );
}

/**
 * Implements hook_hosting_service_type()
 *
 * @TODO: After we get a web and DB container work on generic docker containers.
 */
//function hosting_docker_server_hosting_service_type() {
//  return array(
//    'docker' => array(
//      'title' => t('Docker'),
//    ),
//  );
//}

/**
 * Implements hook_form_alter().
 */
function hosting_docker_server_form_hosting_settings_alter(&$form, &$form_state, $form_id)
{
  $form['hostmaster_container_id'] = array(
    '#title' => t('Docker Container ID of the Hostmaster web container'),
    '#description' => t('In order for Aegir to connect to database servers, it needs to be in the same network. Enter the container ID of this hostmaster\'s web container so that we can add it to the networks created for each server node that enables docker services. To find the container ID, run <code>docker ps</code> and look for the aegir/hostmaster image.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('hostmaster_container_id', ''),
  );
  
}

/**
 * Implements hook_hosting_TASK_OBJECT_context_options().
 *
 * Load hostmaster container ID variable into drush options for server contexts.
 */
function hosting_docker_server_hosting_server_context_options(&$task)
{
  $task->options['hostmaster_container_id'] = variable_get('hostmaster_container_id', NULL);
}